version: '3.8'
services:
  web:
    build: .
    environment:
      - REDIS_HOST=redis
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
  redis:
    restart: unless-stopped
    image: redis:7.0.5-alpine
    expose:
      - 6379