# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\main.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(760, 480)
        MainWindow.setMinimumSize(QtCore.QSize(760, 480))
        MainWindow.setMaximumSize(QtCore.QSize(760, 480))
        MainWindow.setStyleSheet("background-color: rgb(77, 77, 127);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.circularProgressBar_Main = QtWidgets.QFrame(self.centralwidget)
        self.circularProgressBar_Main.setGeometry(QtCore.QRect(20, 60, 240, 240))
        self.circularProgressBar_Main.setStyleSheet("background-color: none;")
        self.circularProgressBar_Main.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.circularProgressBar_Main.setFrameShadow(QtWidgets.QFrame.Raised)
        self.circularProgressBar_Main.setObjectName("circularProgressBar_Main")
        self.circularProgressCPU = QtWidgets.QFrame(self.circularProgressBar_Main)
        self.circularProgressCPU.setGeometry(QtCore.QRect(10, 10, 220, 220))
        self.circularProgressCPU.setStyleSheet("QFrame{\n"
"    border-radius: 110px;\n"
"    background-color: qconicalgradient(cx:0.5, cy:0.5, angle:90, stop:0.400 rgba(85, 170, 255, 255), stop:0.395 rgba(255, 255, 255, 0));\n"
"}")
        self.circularProgressCPU.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.circularProgressCPU.setFrameShadow(QtWidgets.QFrame.Raised)
        self.circularProgressCPU.setObjectName("circularProgressCPU")
        self.circularBg = QtWidgets.QFrame(self.circularProgressBar_Main)
        self.circularBg.setGeometry(QtCore.QRect(10, 10, 220, 220))
        self.circularBg.setStyleSheet("QFrame{\n"
"    border-radius: 110px;\n"
"    background-color: rgba(85, 85, 127, 100);\n"
"}")
        self.circularBg.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.circularBg.setFrameShadow(QtWidgets.QFrame.Raised)
        self.circularBg.setObjectName("circularBg")
        self.circularContainer = QtWidgets.QFrame(self.circularProgressBar_Main)
        self.circularContainer.setGeometry(QtCore.QRect(25, 25, 190, 190))
        self.circularContainer.setBaseSize(QtCore.QSize(0, 0))
        self.circularContainer.setStyleSheet("QFrame{\n"
"    border-radius: 95px;\n"
"    background-color: rgb(58, 58, 102);\n"
"}")
        self.circularContainer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.circularContainer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.circularContainer.setObjectName("circularContainer")
        self.layoutWidget = QtWidgets.QWidget(self.circularContainer)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 40, 171, 137))
        self.layoutWidget.setObjectName("layoutWidget")
        self.infoLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.infoLayout.setContentsMargins(0, 0, 0, 0)
        self.infoLayout.setObjectName("infoLayout")
        self.labelAplicationName = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(10)
        self.labelAplicationName.setFont(font)
        self.labelAplicationName.setStyleSheet("color: #FFFFFF; background-color: none;")
        self.labelAplicationName.setAlignment(QtCore.Qt.AlignCenter)
        self.labelAplicationName.setObjectName("labelAplicationName")
        self.infoLayout.addWidget(self.labelAplicationName, 0, 0, 1, 1)
        self.labelPercentageCPU = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(30)
        self.labelPercentageCPU.setFont(font)
        self.labelPercentageCPU.setStyleSheet("color: rgb(115, 185, 255); padding: 0px; background-color: none;")
        self.labelPercentageCPU.setAlignment(QtCore.Qt.AlignCenter)
        self.labelPercentageCPU.setIndent(-1)
        self.labelPercentageCPU.setObjectName("labelPercentageCPU")
        self.infoLayout.addWidget(self.labelPercentageCPU, 1, 0, 1, 1)
        self.labelCredits = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(8)
        self.labelCredits.setFont(font)
        self.labelCredits.setStyleSheet("color: rgb(148, 148, 216); background-color: none;")
        self.labelCredits.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCredits.setObjectName("labelCredits")
        self.infoLayout.addWidget(self.labelCredits, 2, 0, 1, 1)
        self.circularBg.raise_()
        self.circularProgressCPU.raise_()
        self.circularContainer.raise_()
        self.circularProgressBar_Main_3 = QtWidgets.QFrame(self.centralwidget)
        self.circularProgressBar_Main_3.setGeometry(QtCore.QRect(500, 60, 240, 240))
        self.circularProgressBar_Main_3.setStyleSheet("background-color: none;")
        self.circularProgressBar_Main_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.circularProgressBar_Main_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.circularProgressBar_Main_3.setObjectName("circularProgressBar_Main_3")
        self.label = QtWidgets.QLabel(self.circularProgressBar_Main_3)
        self.label.setGeometry(QtCore.QRect(20, 10, 181, 16))
        self.label.setStyleSheet("color: rgb(115, 185, 255); font-size: 12px; padding-left: 2px; padding-right: 2px; border: none;")
        self.label.setObjectName("label")
        self.widget = QtWidgets.QWidget(self.circularProgressBar_Main_3)
        self.widget.setGeometry(QtCore.QRect(40, 50, 151, 141))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioButton = QtWidgets.QRadioButton(self.widget)
        self.radioButton.setStyleSheet("color: rgb(115, 185, 255); font-size: 12px; padding-left: 2px; padding-right: 2px; border: none;")
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(self.widget)
        self.radioButton_2.setStyleSheet("color: rgb(115, 185, 255); font-size: 12px; padding-left: 2px; padding-right: 2px; border: none;")
        self.radioButton_2.setObjectName("radioButton_2")
        self.verticalLayout.addWidget(self.radioButton_2)
        self.radioButton_3 = QtWidgets.QRadioButton(self.widget)
        self.radioButton_3.setStyleSheet("color: rgb(115, 185, 255); font-size: 12px; padding-left: 2px; padding-right: 2px; border: none;")
        self.radioButton_3.setObjectName("radioButton_3")
        self.verticalLayout.addWidget(self.radioButton_3)
        self.label_title = QtWidgets.QLabel(self.centralwidget)
        self.label_title.setGeometry(QtCore.QRect(60, 10, 641, 50))
        self.label_title.setStyleSheet("color: rgb(115, 185, 255); background-color: none; font-size: 22px;")
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 320, 721, 151))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "System Monitor"))
        self.labelAplicationName.setText(_translate("MainWindow", "<strong>CPU</strong> USAGE"))
        self.labelPercentageCPU.setText(_translate("MainWindow", "<p align=\"center\"><span style=\" font-size:50pt;\">60</span><span style=\" font-size:40pt; vertical-align:super;\">%</span></p>"))
        self.labelCredits.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.label.setText(_translate("MainWindow", "Время обновления графика"))
        self.radioButton.setText(_translate("MainWindow", "1 секунда"))
        self.radioButton_2.setText(_translate("MainWindow", "10 секунд"))
        self.radioButton_3.setText(_translate("MainWindow", "1 минута"))
        self.label_title.setText(_translate("MainWindow", "System Monitor"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
